# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-26 12:42
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('level', '-created')},
        ),
        migrations.AlterField(
            model_name='comment',
            name='ancestors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), db_index=True,
                                                            size=None),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='object_id',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='historicalcomment',
            name='ancestors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(), db_index=True,
                                                            size=None),
        ),
    ]
